### ISSUE TITLE
Defect - dependencyFile along with DependencyResolver leads to NPE

### ISSUE THREAD

**Issue by dennis-behm** [IBM/dbb-zappbuild#229]
With zappbuild release 2.5.0 a defect was introduced, when passing an dependencyFile to the build framework. 

The defect does **not** affect users using the `useSearchConfiguration` leveraging the new dependency resolver APIs - SearchPathDependencyResolver.

```
*** Building file MortgageApplication/cobol/epsmlist.cbl
*** Creating dependency resolver for MortgageApplication/cobol/epsmlist.cbl with [{"library": "SYSLIB", "searchPath": [ {"sourceDir": "/u/dbehm/userBuild", "directory": "MortgageApplication/copybook"} ]                }] rules
java.lang.NullPointerException
at com.ibm.dbb.dependency.DependencyResolver.getLogicalFile(DependencyResolver.java:300)
at com.ibm.dbb.dependency.DependencyResolver.getLogicalFile(DependencyResolver.java:245)
at Cobol$_run_closure1.doCall(Cobol.groovy:59)
at Cobol.run(Cobol.groovy:41)
```

**Comment by drbruce-git** [comment]
Fix has been merged into `main` via https://github.com/IBM/dbb-zappbuild/pull/231
