### ISSUE TITLE
ZUnitConfig.groovy language script fails when there is no PLAYBACK file reference

### ISSUE THREAD

**Issue by dennis-behm** [IBM/dbb-zappbuild#309]
Both in both streams, the ZUnitConfig.groovy script is failing with a NPE, when no Playbackfile reference exits.

```
java.lang.NullPointerException: Cannot invoke method getAt() on null object
	at ZunitConfig$_run_closure1.doCall(ZunitConfig.groovy:66)
	at ZunitConfig.run(ZunitConfig.groovy:31)
	at ZunitConfig$run.callCurrent(Unknown Source)
	at com.ibm.dbb.groovy.ScriptLoader._run(ScriptLoader.groovy:124)
	at com.ibm.dbb.groovy.ScriptLoader$_run$0.call(Unknown Source)
	at com.ibm.dbb.groovy.ScriptLoader.runScript(ScriptLoader.groovy:81)
	at build$_run_closure1.doCall(build.groovy:61)
	at build.run(build.groovy:53)
```

It misses to return a false value along the null object.

**Comment by dennis-behm** [comment]
resolved via #310
