### ISSUE TITLE
zAppBuild Test framework failing with ClassCastException

### ISSUE THREAD

**Issue by dennis-behm** [IBM/dbb-zappbuild#316]
The test framework is failing with a ClassCassException when an error state is detected:

```
Caught: java.lang.ClassCastException: java.lang.Boolean incompatible with java.lang.String
java.lang.ClassCastException: java.lang.Boolean incompatible with java.lang.String
	at com.ibm.dbb.build.BuildProperties.put(BuildProperties.java:66)
	at impactBuild_renaming.validateImpactBuild(impactBuild_renaming.groovy:116)
	at impactBuild_renaming$_run_closure1.doCall(impactBuild_renaming.groovy:59)
	at impactBuild_renaming.run(impactBuild_renaming.groovy:39)
```

**Comment by dennis-behm** [comment]
Additional findings for a test setup which is not passing the `--propFiles` argument to the test framework: 

Missing implementation of this case at 

https://github.com/IBM/dbb-zappbuild/blob/83fbf1989b10f52319c1fb13757a06664209b13b/test/testScripts/impactBuild_deletion.groovy#L28

https://github.com/IBM/dbb-zappbuild/blob/83fbf1989b10f52319c1fb13757a06664209b13b/test/testScripts/impactBuild_deletion.groovy#L44

https://github.com/IBM/dbb-zappbuild/blob/83fbf1989b10f52319c1fb13757a06664209b13b/test/testScripts/impactBuild_properties.groovy#L28

https://github.com/IBM/dbb-zappbuild/blob/83fbf1989b10f52319c1fb13757a06664209b13b/test/testScripts/impactBuild_properties.groovy#L44
