### ISSUE TITLE
When zUnit is not enabled the zUnit tests source code source failed to build

### ISSUE THREAD

**Issue by jbyibm** [IBM/dbb-zappbuild#81]
If we have zUnit test in an application repository and have `file.properties` setup to build these files the build can fail if we want to disable zUnit.

```
IKJ56228I DATA SET NAZARE.TUTO.GENAPP.TEST.COBOL NOT IN CATALOG OR CATALOG CAN NOT BE ACCESSED    
Caught: com.ibm.dbb.build.BuildException: java.io.IOException: com.ibm.dbb.build.BuildException: BGZTK0016E An error occurred running BPXWDYN command 'free dd(SYS00019)'.
com.ibm.dbb.build.BuildException: java.io.IOException: com.ibm.dbb.build.BuildException: BGZTK0016E An error occurred running BPXWDYN command 'free dd(SYS00019)'.
	at com.ibm.dbb.build.CopyToPDS.execute(CopyToPDS.java:89)
	at com.ibm.dbb.build.IExecute$execute.call(Unknown Source)
	at BuildUtilities.copySourceFiles(BuildUtilities.groovy:75)
	at BuildUtilities$copySourceFiles$8.call(Unknown Source)
	at Cobol$_run_closure1.doCall(Cobol.groovy:44)
	at Cobol.run(Cobol.groovy:34)
	at Cobol$run.callCurrent(Unknown Source)
	at com.ibm.dbb.groovy.ScriptLoader._run(ScriptLoader.groovy:124)
	at com.ibm.dbb.groovy.ScriptLoader$_run$1.call(Unknown Source)
	at com.ibm.dbb.groovy.ScriptLoader.runScript(ScriptLoader.groovy:81)
	at build$_run_closure1.doCall(build.groovy:55)
	at build.run(build.groovy:47)
```

Even if we disable zUnit the zUnit test source code is in the build list but the TEST PDS is not created.

I think that when we disable zUnit during DBB build we should not build the zUnit tests source code.

@dennis-behm FYI.

**Comment by jbyibm** [comment]
@dennis-behm  Just a reminder. Today I had a user that were facing to this issue today with https://github.com/IBM/dbb-pipeline/tree/master/cics-genapp when zUnit is not activated.

**Comment by jbyibm** [comment]
@wfezzani FYI

**Comment by dennis-behm** [comment]
@jbyibm there is already a pending PR on this from @EmanuP : #78 

It suggests to make the creation of datasets **conditional** to the existance of  tests in the build list, instead of the property `runzTests` . I like this approach, because running and building is actually two different steps.

@EmanuP would you mind to just add the small enhancement, I had suggested?

**Comment by dennis-behm** [comment]
This is resolved via the a previous PR.
